### ISSUE TITLE
Error validating hashes, Rails 4!

### ISSUE THREAD

**Issue by emmx** [brycesenz/validates_serialized#5]
I'm getting an error validating serialized hashes, but I haven't tried anything else yet so it could be happening for other types too.

The code I used is pretty much the same as in the README here, the relevant part is:

``` ruby
serialize :ratings, Hash
validates_hash_values_with :ratings, numericality: { greater_than: 0 }
```

The error I'm getting is:

```
NoMethodError: undefined method `new' for :ratings:Symbol
~/.rvm/gems/ruby-2.2.1/gems/validates_serialized-0.0.8/lib/validates_serialized/validators/serialized_validator.rb:12:in `block in initialize'
~/.rvm/gems/ruby-2.2.1/gems/validates_serialized-0.0.8/lib/validates_serialized/validators/serialized_validator.rb:11:in `each'
~/.rvm/gems/ruby-2.2.1/gems/validates_serialized-0.0.8/lib/validates_serialized/validators/serialized_validator.rb:11:in `initialize'
~/.rvm/gems/ruby-2.2.1/gems/validates_serialized-0.0.8/lib/validates_serialized/validators/hash_validator.rb:22:in `new'
~/.rvm/gems/ruby-2.2.1/gems/validates_serialized-0.0.8/lib/validates_serialized/validators/hash_validator.rb:22:in `validates_hash_values_with'
...
```

Some versions that may be relevant:

```
Using activesupport 4.2.1
Using activemodel 4.2.1
Using activerecord 4.2.1
Using dm-core 1.2.1
Using dm-validations 1.2.0
Using pg 0.18.3
Using rails 4.2.1
Using spring 1.4.0
Using validates_serialized 0.0.8
```

Any idea?

**Comment by emmx** [comment]
Uh?

**Comment by brycesenz** [comment]
I apologize that I've been busy with other projects; I'll take a look in the next few days.

**Comment by brycesenz** [comment]
Ah, I see what's off - my documentation was wrong, because I'm an idiot.  Try this - 

```
serialize :ratings, Hash
validates_hash_values :ratings, numericality: { greater_than: 0 }
```

Does that work?
